---
# tasks file for monitoring

- name: Pull the Docker image
  docker_image:
    name: jasonrivers/nagios 

- name: Create the docker container of the above
  docker_container:
    name: shark-monitoring
    image: jasonrivers/nagios 
    state: present
    restart: yes
    ports:
     - "0.0.0.0:81:80/tcp"
    volumes:
      - /shark
   
- name: Synchronizing the nagios-container-config
  synchronize:
    src: nagios-container-conf
    dest: /shark/monitoring/
  
- name: Adding the cgi.cgi file containing our custom auth
  template:
   src: cgi.cfg
   dest: /shark/monitoring/nagios-container-conf/cgi.cfg

- name: Start the nifi container
  docker_container:
   name: shark-monitoring
   state: started

- name: Unpacking nagios-plugins zip file into temp
  unarchive:
   src: nagios-plugins-2.3.3.tar.gz
   dest: /tmp
   
- name: Configuring, making and install the above
  shell: cd /tmp/nagios-plugins-2.3.3 && ./configure && make && make install 

- name: Copying the custom check service command
  copy:
   src: check_service
   dest: /usr/local/nagios/libexec/
   mode: 0755

- name: Copying the apache drill check
  copy:
   src: check_apache_drill_row_count.py
   dest: /usr/local/nagios/libexec/
   mode: 0755 
 
- name: Delete nagios monitoring file (it wasn't being deleted for crap reason.....)
  file:
    state: absent
    path: /usr/local/nagios/etc/conf.d/shark_monitoring.cfg

- name: Deploying monitoring nagios config file
  copy:
   src: shark_monitoring.cfg
   dest: /usr/local/nagios/etc/conf.d/
   mode: 0755
   force: yes
  notify: restart-nagios
