---
# tasks file for monitoring

- name: Synchronizing the nagios-container-config
  copy:
    src: nagios-etc
    dest: /shark/monitoring/
    
- name: Copying template nagios config file
  template:
   src: shark_monitoring.cfg
   dest: /shark/monitoring/nagios-etc/conf.d/
  
- name: Copying Dockerfiles to build nagios instance
  copy:
   src: Docker-Nagios
   dest: /shark/monitoring/

- name: build container image
  docker_image:
   name: jasonrivers/nagios 
   path: /shark/monitoring/Docker-Nagios
   source: build
   state: present

- name: Create the docker container of the above
  docker_container:
   name: shark-monitoring
   image: jasonrivers/nagios 
   state: present
   restart: yes
   ports:
    - "0.0.0.0:81:80/tcp"
   volumes:
      - /shark:/shark
      - /shark/monitoring/nagios-etc:/opt/nagios/etc/

- name: Start the nifi container
  docker_container:
   name: shark-monitoring
   state: started

- name: Copying the custom check service command
  copy:
   src: check_service
   dest: /shark/monitoring/
   mode: 0755

- name: Copying the apache drill check
  copy:
   src: check_apache_drill_row_count.py
   dest: /shark/monitoring/
   mode: 0755
