---
- name: Setup requirement for the below
  shell: pip install --upgrade setuptools

# tasks file for monitoring
- name: Copying Dockerfiles to build nagios instance
  copy:
   src: Docker-Nagios
   dest: /tmp
  notify: rebuild-docker-image

- name: Building the Nagios container image from the 'jasonrivers/nagios' template. 
  docker_image:
   name: jasonrivers/nagios 
   path: /tmp/Docker-Nagios

- name: Create the docker container of the above
  docker_container:
   name: shark-monitoring
   image: jasonrivers/nagios 
   state: present
   restart: yes
   ports:
    - "0.0.0.0:81:80/tcp"

- name: Start the shark monitoring container
  docker_container:
   name: shark-monitoring
   state: started
