---
- name: Pulling the Nagios container image from the 'jasonrivers/nagios' image. 
  docker_image:
   name: jasonrivers/nagios 

- name: Create the docker container of the above
  docker_container:
   name: shark-monitoring
   image: jasonrivers/nagios 
   state: present
   restart: yes
   ports:
    - "0.0.0.0:81:80/tcp"

- name: Start the shark monitoring container
  docker_container:
   name: shark-monitoring
   state: started
