---
# tasks file for httpd
- name: Install httpd 
  package:
   name: httpd
   
- name: Install httpd development headers.
  package:
   name: httpd-devel.x86_64
   
   
- name: Installation of REMI
  yum: 
   name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
   state: present
   
- name: Config of REMI
  shell: dnf module reset php -y && sudo dnf module enable php:remi-8.0 -y
   
- name: Installing php deps
  package:
   name: php
   state: latest
   
- name: Installing php-cli deps
  package:
   name: php-cli
   state: latest

- name: Installing php-common deps
  package:
   name: php-common
   state: latest

- name: Removing default landing page
  file:
    path: /var/www/html/index.html
    state: absent
  notify: restart-httpd

- name: Adding Shark webroot into config
  copy:
     src: shark.conf
     dest: /etc/httpd/conf.d
  notify: restart-httpd

- firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes

- name: Start httpd on boot, but dont start just yet
  service:
   name: httpd
   state: stopped
   enabled: true
