---
# tasks file for httpd
- name: Install httpd 
  package:
   name: httpd
   
- name: Install apache2 development headers.
  package:
   name: httpd-dev
   
- name: Installing php deps
  package:
   name: "{{ item }}"
  with_items: 
   - php
   - libhttpd-mod-php

- name: Removing default landing page
  file:
    path: /var/www/html/index.html
    state: absent
  notify: restart-httpd

- name: Adding Shark webroot into config
  copy:
     src: shark.conf
     dest: /etc/apache2/conf-enabled/
  notify: restart-apache2

- name: Starting httpd
  service:
   name: httpd 
   state: started

