---
# tasks file for httpd
- name: Install apache2 
  package:
   name: apache2
   
- name: Install apache2 development headers.
  package:
   name: apache2-dev
   
- name: Installing php deps
  package:
   name: "{{ item }}"
  with_items: 
   - php
   - libapache2-mod-php

- name: Removing default landing page
  file:
    path: /var/www/html/index.html
    state: absent
  notify: restart-apache2

- name: Adding Shark webroot into config
  copy:
     src: shark.conf
     dest: /etc/apache2/conf-enabled/
  notify: restart-apache2

- name: Starting apache
  service:
   name: apache2 
   state: started

