---
# tasks file for httpd
- name: Install httpd 
  package:
   name: httpd
   
- name: Install httpd development headers.
  package:
   name: httpd-devel.x86_64
   
- name: Installing php deps
  package:
   name: "{{ item }}"
  with_items: 
   - php

- name: Removing default landing page
  file:
    path: /var/www/html/index.html
    state: absent
  notify: restart-httpd

- name: Adding Shark webroot into config
  copy:
     src: shark.conf
     dest: /etc/httpd/conf.d
  notify: restart-httpd

- name: Starting httpd
  service:
   name: httpd 
   state: started
   
- firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes

