---
# tasks file for codeigniter

- name: Deploying code igniter framework to webroot
  synchronize:
   src: framework
   dest: /var/www/html/
   owner: root
   group: root

- name: Install prereq - php-curl 
  package:
   name: php-curl
   state: latest

- name: Install prereq - php-intl 
  package:
   name: php-intl

- name: Install prereq - php-mbstring  
  package:
   name: php-mbstring

- name: Install prereq - php-xml 
  package:
   name: php-xml
   
- name: Restarting httpd
  service:
   name: httpd
   state: restarted
