---
# tasks file for gitlab

- name: pull an gitlab/gitlab-ce
  docker_image:
    name: gitlab/gitlab-ce

- name: Create the docker container of the above
  docker_container:
   name: shark-gitlab
   image: gitlab/gitlab-ce
   state: present
   restart: yes
   ports:
    - "0.0.0.0:82/tcp"

- name: Start the container
  docker_container:
   name: shark-gitlab
   state: started
