---

# DEV - all services on a single server.

- name: Shark - Preparing server (DEV)
  hosts: shark-dev
  gather_facts: yes
  strategy: free
  become: true
  vars:
   # ---- Monitoring Web UI credentials
   monitoring_webui_auth_user: shark
   monitoring_webui_auth_pass: shark
  roles:
   - server-prep
   - nrpe
   - docker
   - monitoring
   - zookeeper
   - apache-drill
   - rabbitmq
   - gitlab
   - httpd
   - docker
   - base-from-source
   - shark
