---

# PRODUCTION - scaled out services.

######################################
- name: Shark - Preparing servers (PROD)
  hosts: all
  gather_facts: yes
  strategy: free
  become: true
  roles:
   - server-prep
   - nrpe

######################################
- name: Shark - Installing monitoring
  hosts: shark_monitoring
  become: true
  vars:
          # ---- Monitoring Web UI credentials
          monitoring_webui_auth_user: shark
          monitoring_webui_auth_pass: shark
  roles:
  - docker
  - monitoring
  tags: monitoring

######################################
- name: Shark - Installing zookeeper
  hosts: zookeeper_cluster
  become: true
  roles:
  - zookeeper
  tags: zookeeper
  
######################################
- name: Shark - Installing apache-drill
  hosts: apache_drill_cluster
  become: true
  roles:
  - apache-drill
  tags: apache-drill
  
######################################
- name: Shark - Installing rabbitmq
  hosts: rabbitmq_cluster
  become: true
  vars:
            # ---- RabbitMQ Web UI credentials
          rabbitmq_webui_auth_user: shark
          rabbitmq_webui_auth_pass: shark
  roles:
  - rabbitmq
  tags: rabbitmq

######################################
- name: Shark - UI Installation
  hosts: shark_ui
  become: true
  vars:
          # ---- Shark Web UI credentials
          shark_webui_auth_user: shark
          shark_webui_auth_pass: shark
  roles:
   - httpd
   - docker
   - base-from-source
   - shark
  tags: shark_ui
