---
######################################
- name: Shark - Preparing servers
  hosts: all
  gather_facts: yes
  become: true
  roles:
   - server-prep
   - nrpe
   - metricbeat

######################################
- name: Shark - Installing zookeeper
  hosts: zookeeper_cluster
  become: true
  roles:
  - zookeeper
  
######################################
- name: Shark - Installing apache-drill
  hosts: apache_drill_cluster
  become: true
  roles:
  - apache-drill
  
######################################
- name: Shark - Installing rabbitmq
  hosts: rabbitmq_cluster
  become: true
  vars:
            # ---- RabbitMQ Web UI credentials
          rabbitmq_webui_auth_user: shark
          rabbitmq_webui_auth_pass: shark
  roles:
  - rabbitmq

######################################
- name: Shark - Installing gitlab
  hosts: gitlab_cm
  become: true
  roles:
  - docker
  - gitlab

######################################
- name: Shark - Installing Elasticsearch
  hosts: elasticsearch_cluster
  become: true
  roles:
  - elasticsearch

######################################
- name: Shark - Installing kibana
  hosts: kibana_host
  become: true
  roles:
  - kibana

######################################
- name: Shark - UI Installation
  hosts: shark_ui
  become: true
  vars:
          # ---- Shark Web UI credentials
          shark_webui_auth_user: shark
          shark_webui_auth_pass: shark
  roles:
   - httpd
   - docker
   - base-from-source
   - algorithmictradingplatform
          
  ######################################
- name: Shark - Installing monitoring
  hosts: shark_monitoring
  become: true
  vars:
          # ---- Monitoring Web UI credentials
          monitoring_webui_auth_user: shark
          monitoring_webui_auth_pass: shark
  roles:
  - docker
  - monitoring

