---

- name: Algorithmic Platform Trading Role
  hosts: shark-server
  become: true
  vars:
          # ---- Web UI credentials
          webui_auth_user: shark
          webui_auth_pass: shark

          # ---- System variables

          # We're interested in the timezone of the ASX.
          timezone: "Australia/Sydney"
  roles:
  - server-prep
  - rabbitmq
  - httpd
  - base-from-source
  - algorithmictradingplatform
  - zookeeper
  - apache-drill
  - monitoring # Uncomment this if you want to debug Shark.
