---
- name: Shark - Preparing server
  hosts: shark_server
  gather_facts: yes
  strategy: free
  become: true
  roles:
   - server-prep
   - nrpe
   - httpd
   - codeigniter
   - dokuwiki
   - base-from-source
   - shark
