---

# DEV - all services on a single server.

- name: Shark - Preparing server (DEV)
  hosts: all
  gather_facts: yes
  strategy: free
  become: true
  roles:
   - server-prep
   - nrpe
   - docker
   - monitoring
   - zookeeper
   - apache-drill
   - rabbitmq
   - gitlab
   - httpd
   - docker
   - base-from-source
   - shark
