---
- name: Shark - Preparing server
  hosts: shark_server
  gather_facts: yes
  strategy: free
  become: true
  vars:
  
   # ---- Monitoring Web UI credentials
   shark_webui_auth_user: shark
   shark_webui_auth_pass: shark

   instrument_name: "Coin"
   instrument_group_name: "Coin Group"
   
   instrument_name_plural: "Coins"
   instrument_group_name_plural: "Coin Groups"

   # ---- Header/Footer 
   HEADER: '<span class="bold">MARKET:</span> Cryptocurrency, <span class="bold">SECURITIES:</span> CRYPTO TOP 20, <span class="bold">BACKTEST:</span> Moving Average Crossover'
   FOOTER: '<span class="bold">MARKET:</span> Cryptocurrency, <span class="bold">SECURITIES:</span> CRYPTO TOP 20, <span class="bold">BACKTEST:</span> Moving Average Crossover'

   # ---- Configuration repos - to customise shark, clone the below git repos and supply their new locations.
   shark_config_repo: "https://github.com/danielneil/Shark-Config.git"
   shark_plugins_repo: "https://github.com/danielneil/Shark-Plugins.git"
   shark_brokers_repo: "https://github.com/danielneil/Shark-Brokers.git"
   shark_web_repo: "https://github.com/danielneil/Shark-Web.git"
   
   # ---- Mariadb credentials
   mysql_root_password: "shark"

  roles:
   - server-prep
   - httpd
   - mariadb
   - base-from-source
   - shark
   - git-setup
