---

# DEV - all services on a single server.

- name: Shark - Preparing server (DEV)
  hosts: shark-dev
  gather_facts: yes
  strategy: free
  become: true
  vars:
   # ---- Monitoring Web UI credentials
   shark_webui_auth_user: shark
   shark_webui_auth_pass: shark
   
   # ---- Header/Footer 
   HEADER: '<span class="bold">MARKET:</span> Australian Stock Exchange,<span class="bold">SECURITIES:</span> S&P/ASX 20,<span class="bold">STRATEGY:</span> Moving Averages - (BUY: SMA10 > SMA50)'
   FOOTER: '<span class="bold">MARKET:</span> Australian Stock Exchange,<span class="bold">SECURITIES:</span> S&P/ASX 20,<span class="bold">STRATEGY:</span> Moving Averages - (BUY: SMA10 > SMA50)'
   
  roles:
   - server-prep
   - nrpe
   - docker
   - monitoring
   #- zookeeper
   #- apache-drill
   - rabbitmq
   - httpd
   - codeigniter
   - docker
   - dokuwiki
   - base-from-source
   - shark
