---

- name: Algorithmic Trading Platform Role
  hosts: shark-server
  become: true
  vars:
          # ---- Web UI credentials
          webui_auth_user: shark
          webui_auth_pass: shark

          # ---- System variables

          # We're interested in the timezone of the ASX.
          timezone: "Australia/Sydney"
           
  roles:
  - server-prep
  - httpd
  - zookeeper
  - apache-drill
  - rabbitmq
  - docker
  
  # Builds and installs Nagios Core from source. 
  - base-from-source
  
   # Monitors the Shark architecture.
  - monitoring
  
  # The Shark customisations to Nagios Core. 
  - algorithmictradingplatform
