---

- name: Algorithmic Platform Trading Role
  hosts: shark-server
  become: true
  vars:
          # ---- Web UI credentials
          webui_auth_user: shark
          webui_auth_pass: yourswimmingwithsharks

          # ---- System variables

          # We're interested in the timezone of the ASX.
          timezone: "Australia/Sydney"
  roles:
  - server-prep
  - httpd
  - base-from-source
  - automatedtradingplatform
