---
# tasks file for nrpe

- name: Installing nagios-nrpe-server
  package:
   name: nrpe 
   state: latest
   
- name: Starting nagios-nrpe-server
  service:
   name: nrpe 
   state: started
  
- name: Rolling out NRPE Main configuration file
  package:
   src: nrpe.cfg
   dest: /etc/nagios/
   mode: 0644
  notify: restart-nrpe
   
- name: Rolling out Custom NRPE  configuration file
  copy:
    src: custom-nrpe.cfg
    dest: /etc/nagios/nrpe.d/
    mode: 0644
  notify: restart-nrpe  
