---
# tasks file for nrpe

- name: Installing nagios-nrpe-server
  apt:
   name: nagios-nrpe-server
   state: latest
   
- name: Starting nagios-nrpe-server
  service:
   name: nagios-nrpe-server 
   state: started
  
- name: Rolling out NRPE Main configuration file
  template:
   src: nrpe.cfg
   dest: /etc/nagios/
   mode: 0644
  notify: restart-nrpe
   
- name: Rolling out Custom NRPE  configuration file
  copy:
    src: custom-nrpe.cfg
    dest: /etc/nagios/conf.d
    mode: 0644
  notify: restart-nrpe  
