# This is how you apply each check to specifics ticker.

# The structure of this file is important (as in indentation being yaml).

# <ticker>:
#
# <check_unique_name>
#  description: "<Check description - what appears in the web UI>"
#  check_command: <check_command>
#  <check_argument>: <arg>
#  <check_argument>: <arg>
#  <check_argument>: <arg>

AMC:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: AMC
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: AMC
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma
  ticker: AMC
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: AMC
  name: moving_averages.py
   
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: AMC
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000
 
ANZ:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: ANZ
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: ANZ
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: ANZ
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: ANZ
  name: moving_averages.py
  
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: ANZ
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000
  
BHP:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: BHP
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: BHP
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: BHP
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: BHP
  name: moving_averages.py
 
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: BHP
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000

BXB:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: BXB
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: BXB
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: BXB
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: BXB
  name: moving_averages.py
  
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: BXB
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000

CBA:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: CBA
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: CBA
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: CBA
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: CBA
  name: moving_averages.py

 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: CBA
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000

CSL:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: CSL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: CSL
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: CSL
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: CSL
  name: moving_averages.py
 
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: CSL
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000

GMG:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: GMG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: GMG
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: GMG
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: GMG
  name: moving_averages.py
   
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: GMG
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000
   
IAG:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: IAG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: IAG
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: IAG
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: IAG
  name: moving_averages.py
 
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: IAG
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000

MQG:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: MQG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: MQG
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: MQG
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: MQG
  name: moving_averages.py

 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: MQG
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000

NAB:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: NAB
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: NAB
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: NAB
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: NAB
  name: moving_averages.py
   
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: NAB
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000  
   
NCM:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: NCM
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: NCM
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: NCM
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: NCM
  name: moving_averages.py

 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: NCM
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000  

RIO:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: RIO
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: RIO
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: RIO
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: RIO
  name: moving_averages.py
  
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: RIO
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000  

SCG:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: SCG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: SCG
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: SCG
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: SCG
  name: moving_averages.py

 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: SCG
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000  

SUN:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: SUN
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: SUN
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: SUN
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: SUN
  name: moving_averages.py

 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: SUN
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000 

TLS:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: TLS
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: TLS
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: TLS
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: TLS
  name: moving_averages.py

 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: TLS
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000 
 
TCL:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: TCL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: TCL
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: TCL
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: TCL
  name: moving_averages.py
  
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: TCL
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000 
   
WES:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: WES
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: WES
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: WES
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: WES
  name: moving_averages.py
  
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: WES
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000 
  
WBC:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: WBC
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: WBC
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: WBC
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: WBC
  name: moving_averages.py
  
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: WBC
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000 

WPL:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: WPL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: WPL
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: WPL
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: WPL
  name: moving_averages.py
  
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: WPL
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000 
  
WOW:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: WOW
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SMA: [ 50 Day ]"
  check_command: check_sma 
  ticker: WOW
  period: 50

 Simple Moving Average - 5 Days:
  description: "SMA: [ 5 Day ]"
  check_command: check_sma 
  ticker: WOW
  period: 5

 Opportunity Detection: 
  description: "STRATEGY: [ Moving Averages ]"
  check_command: check_strategy
  ticker: WOW
  name: moving_averages.py
  
 Backtesting:
  description: "BACKTEST: [ Moving Averages ]"
  check_command: check_backtest
  ticker: WOW
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000 
