---
# tasks file for apache-drill
   
- name: Ensure group "drill" exists
  group:
    name: drill
    state: present
    
- name: Add drill user
  user:
    name: drill
    shell: /bin/bash
    groups: drill 
    
- name: Downloading apache drill (This is a crap way to do it, but ansible's get_url kept redownload the file slowing everything down)
  shell: cd /shark && wget -N http://apache.mirrors.hoobly.com/drill/drill-1.18.0/apache-drill-1.18.0.tar.gz

- name: Unzipping the above
  unarchive: 
   src: /shark/apache-drill-1.18.0.tar.gz
   dest: /shark/

- name: Install setup tools for python3
  pip:
   name: setuptools
   executable: pip3

- name: Install pydrill 
  pip:
   name: pydrill
   executable: pip3

- name: Installing pandas
  pip:
   name: pandas
   executable: pip3

- name: Copying configuration file
  copy:
   src: drill-override.conf
   dest: /shark/apache-drill-1.18.0/conf/  
   owner: drill 
   group: drill
  notify: restart-drill
   
- name: Copying dfs configuration file
  copy:
   src: storage-plugins-override.conf
   dest: /shark/apache-drill-1.18.0/conf/storage-plugins-override.conf
   owner: drill 
   group: drill 
  notify: restart-drill
  
- name: Copying test jsonFile
  copy:
   src: testFile.json
   dest: /shark/apache-drill-1.18.0/sample-data/
   owner: drill 
   group: drill 
  notify: restart-drill
    
- name: Configuring permissions on the above
  file: 
   dest: /shark/apache-drill-1.18.0
   owner: drill 
   group: drill 
   recurse: yes
   
- name: Adding drill systemd file
  copy:
   src: drill.service
   dest: /etc/systemd/system/

- name: Starting drill
  service:
   name: drill
   state: started
   enabled: true
