---
# tasks file for git-server

- name: Cloning the default config git repo
  git:
   repo: 'https://github.com/danielneil/Shark-Config.git'
   dest: /var/www/git
    
- name: Creating the template host file containing Shark's ip address.
  copy: 
   content: "shark {{ ansible_default_ipv4.address }}"
   dest: "/var/www/git/bin/hosts"
   mode: 0644
  
- name: Reloading config
  shell: cd /var/www/git/bin && ./reload-config.sh
  
- name: Installing gitweb.noarch
  package:
   name: gitweb.noarch
   state: latest

- name: Copying config file
  copy:
   src: gitweb.conf
   dest: /etc/
  
- name: Copying gitweb-httpd.conf file
  copy:
   src: gitweb-httpd.conf
   dest: /etc/httpd/conf.d/
  notify: restart-httpd

- name: Running semanage fcontext and restorecon on /var/www/git 
  shell: sudo semanage fcontext -m -t httpd_sys_rw_content_t "/var/www/git(/.*)?" && restorecon -Rv /var/www/git
