---
# tasks file for git-server

- name: Cloning the default config git repo
  git:
   repo: "{{ shark_config_repo }}"
   dest: /var/www/git

- name: Converting yml into nagios configuration.
  shell: /var/www/git/bin/config/files/convert_configuration.py > /usr/local/nagios/etc/conf.d/shark.cfg

- name: Creating the template host file containing Shark's ip address.
  copy: 
   content: "[shark_server]\n{{ ansible_default_ipv4.address }}"
   dest: "/var/www/git/bin/hosts"
   mode: 0644

- name: Copying back test code - this will need to be dynamic.
  shell: cp -p /var/www/git/backtests/backtest_moving_averages.py /shark/backtests && chmod 777 /shark/backtests/backtest_moving_averages.py

- name: Cloning the default Shark plugins repo
  git:
   repo: "{{ shark_plugins_repo }}"
   dest: /shark/Shark-Plugins
    
- name: Cloning the default Shark plugins repo
  git:
   repo: "{{ shark_brokers_repo }}"
   dest: /shark/Shark-Brokers
    
- name: Installing gitweb.noarch
  package:
   name: gitweb.noarch
   state: latest

- name: Copying config file
  copy:
   src: gitweb.conf
   dest: /etc/
  
- name: Copying gitweb-httpd.conf file
  copy:
   src: gitweb-httpd.conf
   dest: /etc/httpd/conf.d/
  notify: restart-httpd
