- name: Install Elastic apt - https://artifacts.elastic.co/GPG-KEY-elasticsearch key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Adding deb repo
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
   state: present
   update_cache: yes

- name: Installing apt-transport-https 
  apt: 
   name: apt-transport-https
   state: present
