---

- name: Install pip3
  package:
   name: python3-pip
   state: latest
   
- name: Install pip1
  package:
   name: python-pip
   state: latest

- name: Pyalgotrade for backtesting
  package:
   name: pyalgotrade
   executable: pip3

- name: Install Python Requests
  package:
   name: python3-requests
   state: latest

- name: Install pandas which is a prereq for the below
  package:
   name: python-pandas
   state: latest
   
- name: pip3 installing docker-compose
  shell: pip3 install docker-compose
