---

- name: Install pip
  apt:
   name: python3-pip
   state: latest

- name: Pyalgotrade for backtesting
  pip:
   name: pyalgotrade
   executable: pip3

- name: Install Python Requests
  apt:
   name: python3-requests
   state: latest
