---

- name: Install pip3
  apt:
   name: python3-pip
   state: latest
   
- name: Install pip1
  apt:
   name: python-pip
   state: latest

- name: Pyalgotrade for backtesting
  pip:
   name: pyalgotrade
   executable: pip3

- name: Install Python Requests
  apt:
   name: python3-requests
   state: latest

- name: Install pandas which is a prereq for the below
  apt:
   name: python-pandas
   state: latest
