---

- name: Install pip3
  apt:
   name: python3-pip
   state: latest
  ignore_errors: yes
  # We ignore because on the development system, apt can't acquire a lock cause all hosts are the same host.
   
- name: Install pip1
  apt:
   name: python-pip
   state: latest
  ignore_errors: yes
  # We ignore because on the development system, apt can't acquire a lock cause all hosts are the same host.

- name: Pyalgotrade for backtesting
  pip:
   name: pyalgotrade
   executable: pip3

- name: Install Python Requests
  apt:
   name: python3-requests
   state: latest
  ignore_errors: yes
  # We ignore because on the development system, apt can't acquire a lock cause all hosts are the same host.

- name: Install pandas which is a prereq for the below
  apt:
   name: python-pandas
   state: latest
  ignore_errors: yes
  # We ignore because on the development system, apt can't acquire a lock cause all hosts are the same host.
   
- name: pip3 installing docker-compose
  shell: pip3 install docker-compose
  
