---

- name: Install pip3
  apt:
   name: python3-pip
   state: latest
   
- name: Install pip1
  apt:
   name: python-pip
   state: latest

- name: Pyalgotrade for backtesting
  pip:
   name: pyalgotrade
   executable: pip3

- name: Install Python Requests
  apt:
   name: python3-requests
   state: latest

- name: Install pandas which is a prereq for the below
  apt:
   name: python-pandas
   state: latest
   
- name: pip3 installing docker-compose
  shell: sudo pip3 install docker-compose
  
- name: Required for python ansible stuff.
  shell: sudo cp -r /usr/local/lib/python2.7/dist-packages/backports/ssl_match_hostname/ /usr/lib/python2.7/dist-packages/backports
