---
- name: Adding shark group
  group:
    name: shark
    state: present

- name: Adding shark user
  user:
    name: shark
    comment: AlgorithmicTradingPlatform user account
    group: shark
    shell: /bin/false
    home: /shark

- name: Creating shark working directory
  file:
    name: /shark
    owner: shark
    group: shark
    state: directory
    mode: '0775'

- name: Creating strategies working directory
  file:
    name: /shark/strategies
    owner: shark
    group: shark
    state: directory
    mode: '0775'
    
- name: Creating bin working directory
  file:
   name: /shark/bin
   owner: shark
   group: shark
   state: directory
   mode: '0775'

- name: Creating tmp cache directory
  file:
   name: /tmp/.shark
   group: shark
   owner: shark
   state: directory
   mode: '0775'
