---
- name: Adding shark group
  group:
    name: shark
    state: present

- name: Adding shark user
  user:
    name: shark
    comment: AlgorithmicTradingPlatform user account
    group: shark
    shell: /bin/false
    home: /shark
  ignore_errors: yes
  # We ignore because on the development system, apt can't acquire a lock cause all hosts are the same host.

- name: Creating shark working directory
  file:
    name: /shark
    owner: shark
    group: shark
    state: directory

- name: Creating strategies working directory
  file:
    name: /shark/strategies
    owner: shark
    group: shark
    state: directory
    
- name: Creating bin working directory
  file:
   name: /shark/bin
   owner: shark
   group: shark
   state: directory

- name: Creating monitoring working directory
  file:
   name: /shark/monitoring
   owner: shark
   group: shark
   state: directory

- name: Creating our backtest web dir to store the historical back test web files
  file:
   name: /shark/backtest
   owner: shark
   group: shark
   state: directory
   mode: 0777
    
- name: Creating logs  directory
  file:
   name: /shark/logs
   owner: shark
   group: shark
   state: directory

- name: Creating our backtest transactions web dir
  file:
   name: /shark/backtest/transactions
   owner: shark
   group: shark
   state: directory
   mode: 0777
   
- name: Creating our backtest images web dir
  file:
   name: /shark/backtest/images
   owner: shark
   group: shark
   state: directory
   mode: 0777
   
- name: Creating the backtest HTML web dir
  file:
   name: /shark/backtest/html
   owner: shark
   group: shark
   state: directory
   mode: 0777

- name: Creating tmp cache directory
  file:
   name: /tmp/.shark
   group: shark
   owner: shark
   state: directory
