---
- name: Synchronsing ticker data dir
  copy: 
   src: ticker-data
   dest: /shark/
   owner: shark
   group: shark

- name: Synchronsing data in strategies directory
  copy:
    src: strategies
    dest: /shark/
    owner: shark
    group: shark
    mode: 0755


- name: Cloning the default config git repo
  git:
    repo: 'https://github.com/danielneil/Shark-Default-Config.git'
    dest: /tmp

- name: Moving default config into shar dir
  command: mv /tmp/Shark-Default-Config /shark && cd /shark && mv Shark-Default-Config conf

- name: Copying in our nagios ticker config generation script
  copy:
   src: process_tickers.py
   dest: /shark
   owner: shark
   group: shark
   mode: 0755

- name: Installing pyyaml for the above
  apt:
   name: python-yaml
   state: latest

- name: Copying out ticker-config.yml file
  copy:
   src: ticker-config.yml
   dest: /shark
   group: shark
   owner: shark

- name: Copying in custom UI changes - side.php
  template:
   src: ui_patches/side.php
   dest: /tmp/nagios-4.4.6/html

- name: Copying custom logo
  copy:
   src: ui_patches/sblogo.png
   dest: /tmp/nagios-4.4.6/contrib/exfoliation/images/sblogo.png
  notify:
  - rebuild-nagios
  - restart-nagios

- name: Copying main logo
  copy:
   src: ui_patches/logofullsize.png
   dest: /tmp/nagios-4.4.6/contrib/exfoliation/images/
  notify:
  - rebuild-nagios
  - restart-nagios

- name: Copying left hand header UI code
  copy:
   src: ui_patches/cgiutils.c
   dest: /tmp/nagios-4.4.6/cgi
  notify:
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - status.c
  copy:
   src: ui_patches/status.c
   dest: /tmp/nagios-4.4.6/cgi
  notify: 
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - statusdata.c
  copy:
   src: ui_patches/statusdata.c
   dest: /tmp/nagios-4.4.6/common
  notify: 
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - extinfo.c
  copy:
   src: ui_patches/extinfo.c
   dest: /tmp/nagios-4.4.6/cgi
  notify:
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - extinfo.c
  copy:
   src: ui_patches/main.php
   dest: /tmp/nagios-4.4.6/html
  notify:
  - rebuild-nagios
  - restart-nagios


- meta: flush_handlers

- include: website_check.yml

- include: nagios_configuration.yml

- include: check_short.yml

- include: ui_refresh.yml

- include: custom_cgi_footers.yml

- include: trade_manager.yml

- include: strategy_manager.yml

- name: Running plugin smoke tests
  shell: cd /shark/plugins/ && ./smoke_tests.py
  register: tests_results

- debug: 
        var: tests_results.stdout_lines
