---
- name: Setting credentials for web UI
  shell: htpasswd -b -c /usr/local/nagios/etc/htpasswd.users {{ shark_webui_auth_user }} {{ shark_webui_auth_pass }}

- name: Copying our custom cgi file which enables the above user with access
  template:
    src: cgi.cfg
    dest: /usr/local/nagios/etc/        
    owner: nagios
    group: nagios

- name: Creating our conf.d directory
  file:
    path: /usr/local/nagios/etc/conf.d
    owner: nagios
    group: nagios
    state: directory

- name: Copying our custom nagios configuration
  template: 
   src: nagios.cfg
   dest: /usr/local/nagios/etc/
   owner: nagios
   group: nagios

- name: Checking out the shark plugins from the github repo
  git:
    repo: https://github.com/danielneil/Shark-Plugins.git
    dest: /shark/
   
- name: Adding our custom nagios commands file
  copy:
   src: commands.cfg
   dest: /usr/local/nagios/etc/conf.d/
   owner: nagios
   group: nagios

- name: Restart httpd
  service: 
   name: httpd
   state: restarted

- name: Restart / Start nagios
  service:
   name: nagios
   state: restarted
